export const data = [
  {
    house: 1,
    entrances: [
      {
        number: 1,
        apartments: [
          // 16 этаж
          { number: 136, floor: 16, position: 1, info: "", color: "#FFFFFF" },
          { number: 137, floor: 16, position: 2, info: "", color: "#FFFFFF" },
          { number: 138, floor: 16, position: 3, info: "", color: "#FFFFFF" },
          { number: 139, floor: 16, position: 4, info: "", color: "#FFFFFF" },
          // 15 этаж пустой
          { number: 132, floor: 14, position: 1, info: "", color: "#FFFFFF" },
          { number: 133, floor: 14, position: 2, info: "", color: "#FFFFFF" },
          { number: 134, floor: 14, position: 3, info: "Irina_hoh", color: "#FFFFFF" },
          { number: 135, floor: 14, position: 4, info: "", color: "#FFFFFF" },
          // 13 этаж
          { number: 123, floor: 13, position: 1, info: "", color: "#FFFFFF" },
          { number: 124, floor: 13, position: 2, info: "", color: "#FFFFFF" },
          { number: 125, floor: 13, position: 3, info: "", color: "#FFFFFF" },
          { number: 126, floor: 13, position: 4, info: "Артем", color: "#FFFFFF" },
          { number: 127, floor: 13, position: 5, info: "", color: "#FFFFFF" },
          { number: 128, floor: 13, position: 6, info: "", color: "#FFFFFF" },
          { number: 129, floor: 13, position: 7, info: "@BEARSHAMAN13", color: "#FFFFFF" },
          { number: 130, floor: 13, position: 8, info: "", color: "#FFFFFF" },
          { number: 131, floor: 13, position: 9, info: "@Evgeniya_Golishenko", color: "#FFFFFF" },
          // 12 этаж
          { number: 114, floor: 12, position: 1, info: "Anton Surmach", color: "#FFFFFF" },
          { number: 115, floor: 12, position: 2, info: "", color: "#FFFFFF" },
          { number: 116, floor: 12, position: 3, info: "", color: "#FFFFFF" },
          { number: 117, floor: 12, position: 4, info: "/Dontwriteme_pls", color: "#FFFFFF" },
          { number: 118, floor: 12, position: 5, info: "", color: "#FFFFFF" },
          { number: 119, floor: 12, position: 6, info: "", color: "#FFFFFF" },
          { number: 120, floor: 12, position: 7, info: "", color: "#FFFFFF" },
          { number: 121, floor: 12, position: 8, info: "", color: "#FFFFFF" },
          { number: 122, floor: 12, position: 9, info: "", color: "#FFFFFF" },
          // 11 этаж
          { number: 105, floor: 11, position: 1, info: "", color: "#FFFFFF" },
          { number: 106, floor: 11, position: 2, info: "", color: "#FFFFFF" },
          { number: 107, floor: 11, position: 3, info: "", color: "#FFFFFF" },
          { number: 108, floor: 11, position: 4, info: "", color: "#FFFFFF" },
          { number: 109, floor: 11, position: 5, info: "", color: "#FFFFFF" },
          { number: 110, floor: 11, position: 6, info: "", color: "#FFFFFF" },
          { number: 111, floor: 11, position: 7, info: "", color: "#FFFFFF" },
          { number: 112, floor: 11, position: 8, info: "", color: "#FFFFFF" },
          { number: 113, floor: 11, position: 9, info: "", color: "#FFFFFF" },
          // 10 этаж
          { number: 96, floor: 10, position: 1, info: "", color: "#FFFFFF" },
          { number: 97, floor: 10, position: 2, info: "", color: "#FFFFFF" },
          { number: 98, floor: 10, position: 3, info: "", color: "#FFFFFF" },
          { number: 99, floor: 10, position: 4, info: "", color: "#FFFFFF" },
          { number: 100, floor: 10, position: 5, info: "", color: "#FFFFFF" },
          { number: 101, floor: 10, position: 6, info: "", color: "#FFFFFF" },
          { number: 102, floor: 10, position: 7, info: "Mashylik", color: "#FFFFFF" },
          { number: 103, floor: 10, position: 8, info: "Алена Хвостова", color: "#FFFFFF" },
          { number: 104, floor: 10, position: 9, info: "", color: "#FFFFFF" },
          // 9 этаж
          { number: 87, floor: 9, position: 1, info: "", color: "#FFFFFF" },
          { number: 88, floor: 9, position: 2, info: "", color: "#FFFFFF" },
          { number: 89, floor: 9, position: 3, info: "McDuck8", color: "#FFFFFF" },
          { number: 90, floor: 9, position: 4, info: "", color: "#FFFFFF" },
          { number: 91, floor: 9, position: 5, info: "", color: "#FFFFFF" },
          { number: 92, floor: 9, position: 6, info: "Виталий и Татьяна", color: "#FFFFFF" },
          { number: 93, floor: 9, position: 7, info: "Вероника", color: "#FFFFFF" },
          { number: 94, floor: 9, position: 8, info: "", color: "#FFFFFF" },
          { number: 95, floor: 9, position: 9, info: "", color: "#FFFFFF" },
          // 8 этаж
          { number: 78, floor: 8, position: 1, info: "", color: "#FFFFFF" },
          { number: 79, floor: 8, position: 2, info: "", color: "#FFFFFF" },
          { number: 80, floor: 8, position: 3, info: "", color: "#FFFFFF" },
          { number: 81, floor: 8, position: 4, info: "lekontseva_lena", color: "#FFFFFF" },
          { number: 82, floor: 8, position: 5, info: "@MinchevaDasha", color: "#FFFFFF" },
          { number: 83, floor: 8, position: 6, info: "", color: "#FFFFFF" },
          { number: 84, floor: 8, position: 7, info: "", color: "#FFFFFF" },
          { number: 85, floor: 8, position: 8, info: "", color: "#FFFFFF" },
          { number: 77, floor: 8, position: 9, info: "", color: "#FFFFFF" },
          // 7 этаж
          { number: 68, floor: 7, position: 1, info: "", color: "#FFFFFF" },
          { number: 69, floor: 7, position: 2, info: "", color: "#FFFFFF" },
          { number: 70, floor: 7, position: 3, info: "Катерина", color: "#FFFFFF" },
          { number: 71, floor: 7, position: 4, info: "", color: "#FFFFFF" },
          { number: 72, floor: 7, position: 5, info: "", color: "#FFFFFF" },
          { number: 73, floor: 7, position: 6, info: "", color: "#FFFFFF" },
          { number: 74, floor: 7, position: 7, info: "", color: "#FFFFFF" },
          { number: 75, floor: 7, position: 8, info: "", color: "#FFFFFF" },
          { number: 76, floor: 7, position: 9, info: "", color: "#FFFFFF" },
          // 6 этаж
          { number: 58, floor: 6, position: 1, info: "", color: "#FFFFFF" },
          { number: 59, floor: 6, position: 2, info: "@pelmen87", color: "#FFFFFF" },
          { number: 60, floor: 6, position: 3, info: "", color: "#FFFFFF" },
          { number: 61, floor: 6, position: 4, info: "@Dariya", color: "#FFFFFF" },
          { number: 62, floor: 6, position: 5, info: "", color: "#FFFFFF" },
          { number: 63, floor: 6, position: 6, info: "", color: "#FFFFFF" },
          { number: 64, floor: 6, position: 7, info: "Светлана", color: "#FFFFFF" },
          { number: 65, floor: 6, position: 8, info: "", color: "#FFFFFF" },
          { number: 67, floor: 6, position: 9, info: "", color: "#FFFFFF" },
          // 5 этаж
          { number: 48, floor: 5, position: 1, info: "", color: "#FFFFFF" },
          { number: 49, floor: 5, position: 2, info: "", color: "#FFFFFF" },
          { number: 50, floor: 5, position: 3, info: "@anton_kondratev", color: "#FFFFFF" },
          { number: 51, floor: 5, position: 4, info: "@kris_246", color: "#FFFFFF" },
          { number: 52, floor: 5, position: 5, info: "", color: "#FFFFFF" },
          { number: 53, floor: 5, position: 6, info: "", color: "#FFFFFF" },
          { number: 54, floor: 5, position: 7, info: "@EkaterinaKasanseva", color: "#FFFFFF" },
          { number: 55, floor: 5, position: 8, info: "", color: "#FFFFFF" },
          { number: 57, floor: 5, position: 9, info: "", color: "#FFFFFF" },
          // 4 этаж
          { number: 38, floor: 4, position: 1, info: "", color: "#FFFFFF" },
          { number: 39, floor: 4, position: 2, info: "", color: "#FFFFFF" },
          { number: 40, floor: 4, position: 3, info: "Илья", color: "#FFFFFF" },
          { number: 41, floor: 4, position: 4, info: "", color: "#FFFFFF" },
          { number: 42, floor: 4, position: 5, info: "", color: "#FFFFFF" },
          { number: 43, floor: 4, position: 6, info: "", color: "#FFFFFF" },
          { number: 44, floor: 4, position: 7, info: "", color: "#FFFFFF" },
          { number: 45, floor: 4, position: 8, info: "", color: "#FFFFFF" },
          { number: 47, floor: 4, position: 9, info: "Татьяна", color: "#FFFFFF" },
          // 3 этаж
          { number: 28, floor: 3, position: 1, info: "", color: "#FFFFFF" },
          { number: 29, floor: 3, position: 2, info: "", color: "#FFFFFF" },
          { number: 30, floor: 3, position: 3, info: "", color: "#FFFFFF" },
          { number: 31, floor: 3, position: 4, info: "Суша Наталья", color: "#FFFFFF" },
          { number: 32, floor: 3, position: 5, info: "", color: "#FFFFFF" },
          { number: 33, floor: 3, position: 6, info: "@Ira_Vovk", color: "#FFFFFF" },
          { number: 34, floor: 3, position: 7, info: "Цыганкова Ксения", color: "#FFFFFF" },
          { number: 35, floor: 3, position: 8, info: "", color: "#FFFFFF" },
          { number: 36, floor: 3, position: 9, info: "", color: "#FFFFFF" },
          // 2 этаж
          { number: 18, floor: 2, position: 1, info: "", color: "#FFFFFF" },
          { number: 19, floor: 2, position: 2, info: "Elena Pe", color: "#FFFFFF" },
          { number: 20, floor: 2, position: 3, info: "", color: "#FFFFFF" },
          { number: 21, floor: 2, position: 4, info: "", color: "#FFFFFF" },
          { number: 22, floor: 2, position: 5, info: "", color: "#FFFFFF" },
          { number: 23, floor: 2, position: 6, info: "", color: "#FFFFFF" },
          { number: 24, floor: 2, position: 7, info: "", color: "#FFFFFF" },
          { number: 25, floor: 2, position: 8, info: "", color: "#FFFFFF" },
          { number: 27, floor: 2, position: 9, info: "", color: "#FFFFFF" },
          // 1 этаж
          { number: 8, floor: 1, position: 1, info: "", color: "#FFFFFF" },
          { number: 9, floor: 1, position: 2, info: "", color: "#FFFFFF" },
          { number: 10, floor: 1, position: 3, info: "", color: "#FFFFFF" },
          { number: 11, floor: 1, position: 4, info: "", color: "#FFFFFF" },
          { number: 12, floor: 1, position: 5, info: "@Нат Н", color: "#FFFFFF" },
          { number: 13, floor: 1, position: 6, info: "Баранцева Татьяна", color: "#FFFFFF" },
          { number: 14, floor: 1, position: 7, info: "", color: "#FFFFFF" },
          { number: 15, floor: 1, position: 8, info: "", color: "#FFFFFF" },
          { number: 17, floor: 1, position: 9, info: "", color: "#FFFFFF" },
          // Цокольный этаж
          { number: 1, floor: 0, position: 1, info: "@mandarinduck04", color: "#FFFFFF" },
          { number: 2, floor: 0, position: 2, info: "Меломан", color: "#FFFFFF" },
          { number: 3, floor: 0, position: 3, info: "", color: "#FFFFFF" },
          { number: 4, floor: 0, position: 4, info: "Super_Alba", color: "#FFFFFF" },
          { number: 5, floor: 0, position: 5, info: "", color: "#FFFFFF" },
          { number: 6, floor: 0, position: 6, info: "", color: "#FFFFFF" },
          { number: 7, floor: 0, position: 7, info: "", color: "#FFFFFF" }
        ]
      }
    ]
  }
];